'use client';
// =============================================================================
// app/lessons/seo-metadata/_components/routes-demo.tsx
// Links to the real, generated routes produced by the file conventions.
// -----------------------------------------------------------------------------
// All four targets are RUNNING routes the user can open in a new tab:
//   • /sitemap.xml             — generated by app/sitemap.ts
//   • /robots.txt              — generated by app/robots.ts
//   • /opengraph-image         — generated by app/opengraph-image.tsx
//   • /lessons/seo-metadata/opengraph-image — segment override
//
// Plain anchor tags with `target='_blank'` because we WANT the browser to
// fetch them directly (XML, text/plain, image/png) — no client-side router
// hijack via <Link>.
// =============================================================================

import { useLang } from '../../_components/lang-provider';
import { content } from '../_lib/content';

export default function RoutesDemo() {
    const lang = useLang();
    const t = content[lang].labs.routes;

    const items = [
        { href: '/sitemap.xml', label: t.sitemapLabel, color: 'cyan' },
        { href: '/robots.txt', label: t.robotsLabel, color: 'emerald' },
        { href: '/opengraph-image', label: t.ogImageLabel, color: 'amber' },
        {
            href: '/lessons/seo-metadata/opengraph-image',
            label: t.lessonOgLabel,
            color: 'violet',
        },
    ] as const;

    const colorMap = {
        cyan: 'border-cyan-500/30 bg-cyan-500/5 hover:border-cyan-400/60 text-cyan-200',
        emerald:
            'border-emerald-500/30 bg-emerald-500/5 hover:border-emerald-400/60 text-emerald-200',
        amber: 'border-amber-500/30 bg-amber-500/5 hover:border-amber-400/60 text-amber-200',
        violet: 'border-violet-500/30 bg-violet-500/5 hover:border-violet-400/60 text-violet-200',
    } as const;

    return (
        <div className='grid gap-3 sm:grid-cols-2'>
            {items.map((item) => (
                <a
                    key={item.href}
                    href={item.href}
                    target='_blank'
                    rel='noopener noreferrer'
                    className={`flex items-center justify-between rounded-lg border p-3 transition ${colorMap[item.color]}`}
                >
                    <span className='text-sm'>{item.label}</span>
                    <span className='font-(--font-mono) text-[11px] opacity-70'>
                        {item.href} ↗
                    </span>
                </a>
            ))}
        </div>
    );
}
