// =============================================================================
// app/api/echo/[...path]/route.ts
// CATCH-ALL Route Handler — the "anatomy lab" of Module 4 · Lesson 1.
// -----------------------------------------------------------------------------
// 🧠 Why catch-all
// `[...path]` matches `/api/echo`, `/api/echo/a`, `/api/echo/a/b/c`, etc.
// We don't care about the path semantics — we just want a single endpoint that
// accepts every method and reflects back the dissected `Request` so the
// student can SEE what a Route Handler receives.
//
// 🧠 Why ONE file with seven verb exports
// A `route.ts` lets you export one named async function per HTTP method:
// GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS. If you don't export `OPTIONS`,
// Next auto-implements it (with the right `Allow:` header). If a client sends
// a verb you didn't export, Next answers 405 Method Not Allowed automatically.
//
// 🧠 The `RouteContext<'/api/echo/[...path]'>` helper
// `RouteContext` is a GLOBAL helper auto-generated by `next dev` / `next build`
// / `next typegen`. It derives the `params` type from the route literal — no
// hand-written type, no import. Since Next 15 RC, `ctx.params` is a Promise,
// so we `await` it.
//
// 📚 Docs:
//   node_modules/next/dist/docs/01-app/01-getting-started/15-route-handlers.md
//   node_modules/next/dist/docs/01-app/03-api-reference/03-file-conventions/route.md
// =============================================================================

import type { NextRequest } from 'next/server';

type EchoPayload = {
    method: string;
    url: string;
    pathname: string;
    pathSegments: string[];
    query: Record<string, string | string[]>;
    headers: Record<string, string>;
    cookies: Record<string, string>;
    body: unknown;
    contentType: string | null;
    receivedAt: string;
};

// `searchParams.getAll()` returns `string[]`, so the same key can appear with
// multiple values. We collapse single-value keys to `string` for readability,
// but keep arrays when there's more than one.
function normaliseQuery(
    searchParams: URLSearchParams,
): Record<string, string | string[]> {
    const out: Record<string, string | string[]> = {};
    for (const key of new Set(searchParams.keys())) {
        const values = searchParams.getAll(key);
        out[key] = values.length > 1 ? values : values[0];
    }
    return out;
}

// `Headers` is a Web standard iterable: `for (const [k, v] of headers)`.
// We filter nothing here on purpose — the student should see Next's own added
// headers (`x-forwarded-host`, `x-invoke-path`, etc.) to understand the stack.
function headersToObject(headers: Headers): Record<string, string> {
    const out: Record<string, string> = {};
    headers.forEach((value, key) => {
        out[key] = value;
    });
    return out;
}

// Read the body in a format-aware way. Body is a one-shot stream — read it
// ONCE in exactly ONE form, otherwise the second call throws "Body already
// consumed". For GET / HEAD there is no body at all.
async function readBody(
    request: NextRequest,
): Promise<{ body: unknown; contentType: string | null }> {
    const contentType = request.headers.get('content-type');
    if (request.method === 'GET' || request.method === 'HEAD') {
        return { body: null, contentType };
    }

    try {
        if (contentType?.includes('application/json')) {
            return { body: await request.json(), contentType };
        }
        if (contentType?.includes('application/x-www-form-urlencoded')) {
            const form = await request.formData();
            return { body: Object.fromEntries(form.entries()), contentType };
        }
        if (contentType?.includes('multipart/form-data')) {
            const form = await request.formData();
            const obj: Record<string, unknown> = {};
            for (const [key, value] of form.entries()) {
                obj[key] =
                    value instanceof File
                        ? { name: value.name, size: value.size, type: value.type }
                        : value;
            }
            return { body: obj, contentType };
        }
        const text = await request.text();
        return { body: text.length > 0 ? text : null, contentType };
    } catch (err) {
        return {
            body: { error: err instanceof Error ? err.message : 'parse failed' },
            contentType,
        };
    }
}

// Shared handler. Each verb export below just delegates to this — that's the
// "echo" trick: we don't care which verb fired, only what came with it.
async function echo(
    request: NextRequest,
    ctx: RouteContext<'/api/echo/[...path]'>,
): Promise<Response> {
    // `ctx.params` is a Promise since Next 15 RC.
    const { path } = await ctx.params;
    const { body, contentType } = await readBody(request);

    const payload: EchoPayload = {
        method: request.method,
        url: request.url,
        pathname: request.nextUrl.pathname,
        pathSegments: path,
        query: normaliseQuery(request.nextUrl.searchParams),
        headers: headersToObject(request.headers),
        cookies: Object.fromEntries(
            request.cookies.getAll().map(c => [c.name, c.value]),
        ),
        body,
        contentType,
        receivedAt: new Date().toISOString(),
    };

    // `Response.json()` is a Web-standard shortcut for
    // `new Response(JSON.stringify(x), { headers: { 'content-type': 'application/json' } })`.
    return Response.json(payload, {
        status: 200,
        // CORS-permissive: this is a teaching endpoint. Don't copy this to
        // production without scoping `Access-Control-Allow-Origin`.
        headers: { 'x-handled-by': 'living-notebook/echo' },
    });
}

export const GET = echo;
export const POST = echo;
export const PUT = echo;
export const PATCH = echo;
export const DELETE = echo;
