// =============================================================================
// app/lessons/layout.tsx — SHARED LAYOUT for the whole /lessons/* subtree
// -----------------------------------------------------------------------------
// 🧠 ARCHITECTURE
// A `layout.tsx` file defines UI that wraps EVERY route segment below its
// folder. The critical property of an App Router layout is:
//
//   👉 On navigation between sibling routes, the layout component instance
//      is NOT unmounted. Its React tree (state, scroll position, open
//      portals, mounted client islands) is preserved. Only the `children`
//      slot is swapped.
//
// We exploit that in the Debugging Lab: the `<PersistenceProbe>` Client
// island lives in this layout. Its `useState` counter survives every
// navigation within /lessons/* — visible proof that the layout did not
// unmount.
//
// This file itself is a SERVER COMPONENT (no 'use client'): it does no
// interactive work, it just composes static markup + a client island.
//
// 📚 Docs:
//   node_modules/next/dist/docs/01-app/01-getting-started/03-layouts-and-pages.md
//   node_modules/next/dist/docs/01-app/01-getting-started/04-linking-and-navigating.md
// =============================================================================

import Link from 'next/link';
import LangBar from './_components/lang-bar';
import { LangProvider } from './_components/lang-provider';
import PersistenceProbe from './_components/persistence-probe';

// `LayoutProps<'/lessons'>` is a GLOBAL helper auto-generated by `next dev`,
// `next build`, or `next typegen`. It infers the `children` prop (and any
// `params` / named slots if the route had them). No import is needed —
// these helpers are declared in the generated `.next/types/**` ambient files.
//
// 🧠 LangProvider lives HERE, at the highest layout that covers every lesson.
// The React tree of a layout is not unmounted when you navigate between
// sibling routes, so the language state survives navigation across the whole
// /lessons/* subtree. See app/lessons/context-provider for the lesson that
// explains why we lifted it from per-lesson layouts to here.
export default function LessonsLayout({ children }: LayoutProps<'/lessons'>) {
    return (
        <LangProvider>
            <div className='min-h-full bg-linear-to-b from-slate-950 via-slate-900 to-slate-950 text-slate-100'>
                {/* HEADER — sticky chrome shared by every lesson under /lessons/* */}
                <header className='sticky top-0 z-10 border-b border-slate-800/60 bg-slate-950/70 backdrop-blur'>
                    <div className='mx-auto flex max-w-5xl items-center justify-between gap-3 px-4 py-3 sm:px-6'>
                        <div className='flex items-center gap-3'>
                            {/* `<Link>` from next/link — client-side transition + auto-prefetch */}
                            <Link
                                href='/'
                                className='inline-flex items-center gap-1 rounded-md border border-slate-700/60 bg-slate-900/50 px-2.5 py-1 text-xs font-medium text-slate-300 transition-colors hover:border-slate-600 hover:text-slate-100'
                            >
                                <span aria-hidden>←</span> Home
                            </Link>
                            <span className='font-mono text-xs text-sky-400'>
                                /lessons
                            </span>
                            <span className='hidden text-xs text-slate-500 sm:inline'>
                                laboratorio interattivo
                            </span>
                        </div>

                        <div className='flex items-center gap-3'>
                            {/* Global language switcher — single source of truth for the whole subtree */}
                            <LangBar />
                            {/* Client island — its state PROVES the layout persists across navigations. */}
                            <PersistenceProbe />
                        </div>
                    </div>
                </header>

                <main className='mx-auto max-w-5xl px-4 py-8 sm:px-6 sm:py-12'>
                    {children}
                </main>
            </div>
        </LangProvider>
    );
}
