// =============================================================================
// app/lessons/optimization-media/layout.tsx
// Scoped layout for Module 5 · Lesson 1 — loads Inter (sans) + JetBrains Mono
// (mono) via `next/font/google` and exposes them as CSS variables ONLY for
// this lesson subtree.
// -----------------------------------------------------------------------------
// 🧠 WHY A LAYOUT (not the root layout)
// We could have added these fonts to `app/layout.tsx`, but that would change
// the visual identity of every other lesson built so far. Putting the fonts
// in a NESTED layout scopes them to `/lessons/optimization-media/*` only:
//
//   • The <html>/<body> already mounted by the root layout stay untouched.
//   • The `--font-sans` / `--font-mono` CSS variables only exist inside the
//     wrapper <div> rendered below — outside of this subtree they resolve to
//     "undefined" and Tailwind's font stack falls back to its default chain.
//   • Zero risk of regressing the other 16 lessons.
//
// 🧠 WHY CSS VARIABLES (not className)
// `next/font` exposes two surfaces:
//   1. `font.className` — apply directly to set font-family
//   2. `font.variable`  — exposes a CSS custom property (e.g. `--font-sans`)
//
// Approach (1) is fine for ONE font, but breaks down with two: you can't put
// two competing `font-family` declarations on the same element. Approach (2)
// is the production pattern: the layout publishes the variable, and downstream
// CSS / Tailwind decides where each variable applies (e.g. `font-mono` for
// <pre>, `font-sans` for prose). It also plays nicely with Tailwind v4's
// `@theme` directive — see `app/globals.css` for the bridge.
//
// 🧠 BUILD-TIME SELF-HOSTING
// `next/font/google` does NOT issue a request to fonts.gstatic.com at runtime.
// At BUILD time it downloads the `.woff2` files, hashes them, and serves them
// from `/_next/static/media/...` from your own domain. Three wins:
//   • Privacy (no Google round-trip → GDPR-friendly).
//   • Performance (no third-party DNS + TLS + fetch on the critical path).
//   • Zero FOUT: `display: swap` plus an auto-generated metric-adjusted
//     fallback font that minimises Cumulative Layout Shift while Inter loads.
//
// 📚 Doc: node_modules/next/dist/docs/01-app/01-getting-started/13-fonts.md
// 📚 Doc: node_modules/next/dist/docs/01-app/03-api-reference/02-components/font.md
// =============================================================================

import { Inter, JetBrains_Mono } from 'next/font/google';
import type { ReactNode } from 'react';

// -----------------------------------------------------------------------------
// Inter — UI sans-serif. Variable font (one file covers every weight 100-900),
// so we DO NOT pass a `weight` option. `subsets: ['latin']` keeps the payload
// small (~30 KB) — pick `latin-ext` only if you actually render Cyrillic /
// Vietnamese / extended characters with this font.
// `display: 'swap'` tells the browser to show fallback text first, then swap
// to Inter when it loads. Combined with the auto-generated metric-adjusted
// fallback, the swap is visually seamless.
// `variable: '--font-sans'` exposes a CSS custom property — we still apply
// `sans.className` to the wrapper below so the browser sees Inter being used
// IMMEDIATELY (otherwise dev shows: "preloaded but not used within a few
// seconds of load" — see comment on the wrapper).
// -----------------------------------------------------------------------------
const sans = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-sans',
});

// -----------------------------------------------------------------------------
// JetBrains Mono — monospaced, used for code blocks and inline `<code>`.
// `preload: false` is INTENTIONAL: mono is never an LCP candidate (the first
// monospaced glyph appears below the fold inside snippets), so preloading
// 50 KB of woff2 before paint is pure waste. `display: 'swap'` means the
// browser shows a fallback monospaced font instantly, then swaps to JetBrains
// Mono once it loads — no FOIT, no blocking. This also silences the dev-time
// warning "preloaded using link preload but not used within a few seconds".
// SENIOR RULE OF THUMB: preload ONLY fonts that render above the fold within
// the LCP element.
// -----------------------------------------------------------------------------
const mono = JetBrains_Mono({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-mono',
    preload: false,
});

export default function OptimizationMediaLayout({
    children,
}: {
    children: ReactNode;
}) {
    // The wrapper carries THREE classNames generated by next/font:
    //   • `sans.className`  → applies `font-family: Inter, …` DIRECTLY on this
    //                         element. This is what makes the browser register
    //                         Inter as "in use" the moment the wrapper paints,
    //                         honoring the `<link rel="preload">` emitted by
    //                         next/font and silencing the "preloaded but not
    //                         used" warning.
    //   • `sans.variable`   → also publishes Inter as `var(--font-sans)` so
    //                         downstream components can read it (e.g. Lab 3).
    //   • `mono.variable`   → publishes JetBrains Mono as `var(--font-mono)`.
    //                         Mono itself is NOT applied to the wrapper — it
    //                         is opted into per element via the Tailwind class
    //                         `font-[var(--font-mono)]` (code blocks).
    //
    // Net effect: descendants render in Inter by default; code blocks switch
    // to JetBrains Mono explicitly. The CSS-variables pattern stays intact
    // (Lab 3 still reads both vars) — we just additionally apply sans's
    // className for correct preload behavior.
    return (
        <div className={`${sans.className} ${sans.variable} ${mono.variable}`}>
            {children}
        </div>
    );
}
